head:
  css:
    example: //example.min.css
  js:
    base:
      - xxx
    async:
    defer:

favicon: /favicon.ico

language: zh-CN

alien:
  enable: true
  url: source\_posts\images\alien.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦

bg_image:
  enable: true
  url: source\_posts\images\bg.jpg
  # dark:
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.8

search:
  modal: true
  bg_image: source\_posts\images\bg.jpg
  dark_bg_image: xxx
  # placeholder:

colors:
  primary: '#6200ee'
  # bg: "#F5F5F5"
  selection_bg: '#8e71c1' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:
  
tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  CSS: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'

categories:
  ç¬”è®°: dimgray

social:
  - name: E-Mail
    link: mailto:2405848533@qq.com
    icon: ri:mail-line
    color: '#8E71C1'

banner:
  enable: true
  title: äºŒè¿›åˆ¶çˆªå°
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: true
  content: ç”¨çˆªå°ç¼–è¯‘ä¸–ç•Œçš„æµªæ¼«â€”â€”ç”µå­ä¿¡æ¯ç‹—çš„æˆé•¿å‹è„‘å›è·¯
# å¯é€‰ light | dark | auto | time

mode: auto

font:

medium_zoom: true

cursor:
  enable: false
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: source\_posts\images\bg.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: ri:settings-line

pages:
