head:
  css:
    example: //example.min.css
  js:
    base:
      - xxx
    async:
    defer:

favicon: /favicon.ico

language: zh-CN

avatar:
  enable: true
  url: /images/avatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦ï¼ï¼

bg_image:
  enable: true
  url: /images/background.jpg
  # dark:
  opacity: 0.5

search:
  modal: true
  bg_image: /images/backgroud.jpg
  dark_bg_image: /images/bg.jpg
  # placeholder:

colors:
  primary: '#6200ee'
  # bg: "#F5F5F5"
  selection_bg: '#8e71c1' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:
  
tags:
  C: '#4fc08d'
  C++: '#5298d1'
  stm32: '#026E00'
  Git: '#F14E32'
  Python: '#3776ab'
  VS Code: '#0066B8'
  Hexo: '#0E834D'


categories:
  ç¬”è®°: dimgray
  å­¦ä¹ : saddlebrown
  æ•™ç¨‹: royalblue
  Linux: '#2577b1'

social:
  - name: E-Mail
    link: mailto:2405848533@qq.com
    icon: ri:mail-line
    color: '#8E71C1'

banner:
  enable: true
  title: äºŒè¿›åˆ¶çˆªå°
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: true
  content: ç”¨çˆªå°ç¼–è¯‘ä¸–ç•Œçš„æµªæ¼«â€”â€”ç”µå­ä¿¡æ¯ç‹—çš„æˆé•¿å‹è„‘å›è·¯
# å¯é€‰ light | dark | auto | time

mode: auto


medium_zoom: true

cursor:
  enable: false
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: ri:settings-line

post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: false

post_edit:
  enable: true
  url: https://github.com/1231Lisette/01paw/tree/hexo/source/_posts

# å…³é—­ highlight
highlight:
  enable: false
# å¯ç”¨ prism
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

codeblock:
  copy_btn: true

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: true

lazyload:
  enable: true

footer:
  since: 2025
  icon:
    name: ri:cloud-line
    animated: true
    color: '#93D89F'
  powered:
    enable: true
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2025-02-04T22:15:00'

say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

mourn:
  enable: true
  days:
    - 4-4

pages:
  - name: æˆ‘çš„çŒªçŒª
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

wordcloud:
  enable: true